theme: minima
title: Web Dev Bootcamp
author: wtsaygers1
email: wtsaygers1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My experience in the Awesome Inc U Web Dev Bootcamp for the Spring 2021 class.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
